---
- name: Instalar MSI
  hosts: win1
  tasks:
  - name: Download MSI
    win_get_url:
      url: https://www.7-zip.org/a/7z1604-x64.msi
      dest: C:\Temp\7z1604-x64.msi
  - name: Install MSI
    win_package:
      path: C:\Temp\7z1604-x64.msi
      state: present